### ISSUE TITLE
`echo deadbeef | hashvis` fails

### ISSUE THREAD

**Issue by boredzo** [boredzo/hashvis#1]
```
echo 'deadbeef' | hashvis                                           %/Volumes/RAM Disk(1)
deadbeef
Traceback (most recent call last):
  File "/Volumes/Home/Users/prh/bin/hashvis", line 176, in <module>
    for output_line in hash_to_pic(hash):
  File "/Volumes/Home/Users/prh/bin/hashvis", line 114, in hash_to_pic
    for b in bytes:
  File "/Volumes/Home/Users/prh/bin/hashvis", line 81, in parse_hex
    yield int(byte_hex, 16)
ValueError: invalid literal for int() with base 16: ''
```

Weirdly, copying the hash in question and doing `pbpaste | hashvis` worked just fine.

**Comment by boredzo** [comment]
echo -n deadbeef | hashvis also works.

Seems it's trying to parse the “line” after the last newline?

**Comment by boredzo** [comment]
Output from printing `repr(byte_hex)` and `repr(hex)` after splitting off each byte:

```
'deadbeef\n'
'de' 'adbeef\n'
'ad' 'beef\n'
'be' 'ef\n'
'ef' '\n'
'\n' ''
```
